name: rodbez_yard
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  connectivity_plus: ^5.0.1
  geolocator:
  flutter_launcher_icons: ^0.14.4
  country_pickers: ^3.0.1
  http: ^1.4.0
  pinput: ^5.0.1
  shared_preferences:
  shimmer:
  google_maps_flutter: ^2.12.1
  flutter_svg: ^2.1.0
  flutter_dash: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/icon/bottom_navbar/
    - assets/icon/svg/
    - assets/images/
    - assets/logos/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Italic.ttf
          style: italic
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 800